spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1930
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false